spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/departments/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**
      discovery:
        locator:
          enabled: true
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9191

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

